export const dateNormalizer = (params, name) =>
  params.row[name] ? new Date(params.row[name]).toLocaleDateString() : "";

export const columnsSummaryCards = [
  { field: "id", headerName: "ID", width: 90, hide: true },
  {
    field: "Codigo  establec",
    headerName: "Terminal",
    width: 150,
  },
  {
    field: "Franquicia",
    headerName: "Franquicia",
    width: 150,
    type: "String",
  },
  {
    field: "Fecha de Abono",
    headerName: "Fecha de Abono",
    width: 200,
    type: "date",
    valueGetter: (params) => dateNormalizer(params, "Fecha de Abono"),
  },
  {
    field: "Fecha de proceso",
    headerName: "Fecha de proceso",
    width: 200,
    type: "String",
    valueGetter: (params) => dateNormalizer(params, "Fecha de proceso"),
    hide: true,
  },
  {
    field: "Tipo Transaccion",
    headerName: "Tipo Transaccion",
    width: 150,
    type: "number",
    hide: true,
  },
  {
    field: "Vlr Compras",
    headerName: "Vlr Compras",
    width: 150,
    type: "number",
    hide: true,
  },
  {
    field: "Vlr Iva",
    headerName: "Vlr Iva",
    width: 150,
    type: "number",
    hide: true,
  },
  {
    field: "Vlr Propina",
    headerName: "Vlr Propina",
    width: 150,
    type: "number",
    hide: true,
  },
  {
    field: "Vlr Total",
    headerName: "Vlr Total",
    width: 150,
    type: "number",
  },
  {
    field: "Valor Comision",
    headerName: "Valor Comision",
    width: 150,
    type: "number",
    hide: true,
  },
  {
    field: "Vlr Rete Iva",
    headerName: "Vlr Rete Iva",
    width: 150,
    type: "number",
    hide: true,
  },
  {
    field: "Vlr Rete Ica",
    headerName: "Vlr Rete Ica",
    width: 150,
    type: "number",
    hide: true,
  },
  {
    field: "Valor Rte Fte",
    headerName: "Valor Rte Fte",
    width: 150,
    type: "number",
    hide: true,
  },
  {
    field: "Valor Abono",
    headerName: "Valor Abono",
    width: 150,
    type: "number",
  },
  {
    field: "Cuenta",
    headerName: "Cuenta",
    width: 150,
    type: "number",
    hide: true,
  },
  {
    field: "asociado",
    type: "string",
    headerName: "Asociados",
    width: 150,
    hide: true,
  },
];

export const columnsAllCards = [
  { field: "id", headerName: "ID", width: 90, hide: true },
  { field: "Comercio", type: "number", headerName: "Terminal", width: 120 },
  { field: "Franquicia", type: "string", headerName: "Franquicia", width: 150 },
  {
    field: "F abono",
    type: "date",
    headerName: "Fecha de Abono",
    width: 200,
    hide: true,
    valueGetter: (params) => dateNormalizer(params, "F abono"),
  },
  {
    field: "F vale",
    type: "date",
    headerName: "Fecha de Vale",
    width: 200,
    valueGetter: (params) => dateNormalizer(params, "F vale"),
  },
  {
    field: "F proceso",
    type: "date",
    headerName: "Fecha de Proceso",
    width: 200,
    valueGetter: (params) => dateNormalizer(params, "F proceso"),
    hide: true,
  },
  {
    field: "Tarjeta",
    type: "number",
    headerName: "Tarjeta",
    width: 150,
    hide: true,
  },
  {
    field: "Hora trans",
    type: "number",
    headerName: "Hora trans",
    width: 150,
    hide: true,
  },
  {
    field: "Comprobante",
    type: "number",
    headerName: "Comprobante",
    width: 150,
    hide: true,
  },
  { field: "Autorizacion", headerName: "Autorizacion", width: 150, hide: true },
  {
    field: "Terminal",
    type: "string",
    headerName: "Terminal Especi",
    width: 150,
    hide: true,
  },
  {
    field: "Vlr Compra",
    type: "number",
    headerName: "Vlr Compra",
    width: 150,
    hide: true,
  },
  {
    field: "Vlr Iva",
    type: "number",
    headerName: "Vlr Iva",
    width: 150,
    hide: true,
  },
  {
    field: "Vlr Propina",
    type: "number",
    headerName: "Vlr Propina",
    width: 150,
    hide: true,
  },
  { field: "Vlr Total", type: "number", headerName: "Vlr Total", width: 150 },
  {
    field: "Vlr Comision",
    type: "number",
    headerName: "Vlr Comision",
    width: 150,
    hide: true,
  },
  {
    field: "Vlr Rete Iva",
    type: "number",
    headerName: "Vlr Rete Iva",
    width: 150,
    hide: true,
  },
  {
    field: "Vlr Rete Ica",
    type: "number",
    headerName: "Vlr Rete Ica",
    width: 150,
    hide: true,
  },
  {
    field: "Vlr Rete Fuente",
    type: "number",
    headerName: "Vlr Rete Fuente",
    width: 150,
    hide: true,
  },
  { field: "Vlr Abono", type: "number", headerName: "Vlr Abono", width: 150 },
  {
    field: "T Tarjeta",
    type: "number",
    headerName: "T Tarjeta",
    width: 150,
    hide: true,
  },
  {
    field: "Cuenta",
    type: "number",
    headerName: "Cuenta",
    width: 150,
    hide: true,
  },
  {
    field: "Tipo Transaccion",
    type: "number",
    headerName: "Tipo Transaccion",
    width: 150,
    hide: true,
  },
];

export const columnsAuxiliary = [
  { field: "id", headerName: "ID", width: 90, hide: true },
  {
    field: "COMPROBANTE",
    headerName: "Comprobante",
    width: 150,
    type: "string",
  },
  {
    field: "FECHA",
    headerName: "Fecha",
    width: 150,
    type: "date",
    valueGetter: (params) => dateNormalizer(params, "FECHA"),
  },
  {
    field: "DESCRIPCION",
    headerName: "Descripcion",
    width: 150,
    type: "string",
  },
  { field: "DEBITOS", headerName: "Debitos", width: 150, type: "number" },
  { field: "CREDITOS", headerName: "Creditos", width: 150, type: "number" },
  { field: "FRANQUICIA", headerName: "Franquicia", width: 150, type: "string" },
  {
    field: "FECHA VAOUCHER",
    headerName: "Fecha Voucher",
    width: 150,
    type: "date",
    valueGetter: (params) => dateNormalizer(params, "FECHA VAOUCHER"),
  },
  { field: "TERMINAL", headerName: "Terminal", width: 150 },
];
export const columnsStatement = [
  { field: "id", headerName: "ID", width: 90, hide: true },
  {
    field: "FECHA",
    headerName: "Fecha",
    width: 150,
    type: "date",
    valueGetter: (params) => dateNormalizer(params, "FECHA"),
  },
  {
    field: "DESCRIPCION",
    headerName: "Descripcion",
    width: 150,
    type: "string",
  },
  { field: "TERMINAL", headerName: "Terminal", width: 150, type: "number" },
  { field: "DEBITO", headerName: "Debito", width: 150, type: "number" },
  { field: "CREDITO", headerName: "Credito", width: 150, type: "number" },
  { field: "TIPO", headerName: "Tipo", width: 150, type: "string" },
];
